#!/usr/bin/env bash

if [[ -z $COMPOSE_FILE ]]; then
    /usr/bin/php "$@"
    exit $!
fi

if [[ -z $PHP_SERVICE ]]; then
    php_service='php'
else
    php_service=$PHP_SERVICE
fi

source wrapper

function main() {
    run_service \
        -v composer-home:${DEV_TOOLS_COMPOSER_HOME:-/root/.composer}:ro \
        -v composer-cache:${DEV_TOOLS_COMPOSER_CACHE:-/root/.cache/composer} \
        -v ssh-config:${DEV_TOOLS_SSH_CONFIG:-/root/.ssh}:ro \
        -e COMPOSER_MEMORY_LIMIT=-1 \
        "$php_service" \
        composer \
        "$@"
}

function trap_hooks() {
    script=$(cat "$(which "${*}")")

    exec_service "$php_service" sh -c "$script"

    # time run_service \
    #     -v "$(which "${*}")":/hook.sh \
    #     "$php_service" \
    #     /hook.sh &> null
}

wrapper main "$@"
