#!/usr/bin/env bash

source wrapper

function main() {
    if [[ -z $PHP_SERVICE ]]; then
        echo "Could not find PHP service."

        exit 1
    fi

    # When having permission issues, especially when using older services,
    # try these environment variables
    # -e C_UID=1000
    # -e G_UID=1000
    run_service \
        -v composer-auth:/var/www/.composer:ro \
        -v composer-cache:/var/www/.cache/composer \
        -v ssh-config:/var/www/.ssh:ro \
        -e COMPOSER_MEMORY_LIMIT=-1 \
        -u "$(id -u):$(id -g)" \
        $PHP_SERVICE \
        composer \
        "$@"
}

wrapper main "$@"
