#!/usr/bin/env bash

source wrapper

function main() {
    # @todo: do in advance via generator
    maven_root=$(fd "pom.xml" "$PROJECT_FOLDER")

    arguments=()
    file=0
    for arg in "$@"; do
        if [[ $arg == "-f" ]]; then
            file=1
            continue
        fi

        if [[ $file -eq 1 ]]; then
            maven_root=$arg
            continue
        fi

        arguments+=("$arg")
    done

    docker run --rm \
        -u "$(id -u):$(id -g)" \
        -e MAVEN_CONFIG=/var/maven/.m2 \
        -v "$(dirname "$maven_root")":/usr/src/mymaven \
        -v m2:/var/maven/.m2 \
        -w /usr/src/mymaven \
        maven:latest mvn -Duser.home=/var/maven "${arguments[@]}"
}

wrapper main "$@"

