#!/usr/bin/env bash

source mysqlwrapper

function main() {
    main_parent
    
    output=$(exec_service $MYSQL_SERVICE mysqldump $(credentials) "$@")
    
    if [[ $? -ne 0 ]]; then
        echo "$output" 1>&2
    
        exit 1
    fi
    
    echo "$output"
}

wrapper main "$@"
