#!/usr/bin/env bash

source $XDG_CONFIG_HOME/dockerenv/wrapper

# @todo: node should be backwards compatible, if something fails because of the version
# add checks for node requirements (i.e. if engines is defined)
# @todo: create env var for folder containing package.json (so $(pwd) isn't needed)

function main() {
    docker run --rm \
        -v npm-cache:/home/node/.npm \
        -v ssh-config:/home/node/.ssh:ro \
        -v "$(pwd)":/home/node/app \
        -u "$(id -u):$(id -g)" \
        -w "/home/node/app" \
        -e "TERM=${TERM}" \
        node:19-alpine \
        npm \
        "$@"
}

wrapper main "$@"
