#!/usr/bin/env bash

if [[ -z $COMPOSE_FILE ]]; then
    /usr/bin/php "$@"
    exit $!
fi

if [[ -z $PHP_SERVICE ]]; then
    php_service='php'
else
    php_service=$PHP_SERVICE
fi

source wrapper

function main() {
    exec_service \
        "$php_service" \
        vendor/bin/phpunit \
        "$@"
}

wrapper main "$@"
