#!/usr/bin/env bash

set -e

usage() {
cat <<- EOF
Start a tmux session with application specific environment variables and binaries
Usage:
    startenv [-d|--defaults] [-f|--folder] [-h|--help]
             [-r|--regenerate ] [-v|--verbose]
             <name>
Options:
    -d, --defaults      Source a file with defaults
    -f, --folder        Project folder
    -h, --help          Show this message
    -r, --regenerate    Regenerate cached env variables
    -v, --verbose       Show more info when executing commands
EOF
}

regenerate=0
folder=""
defaults=""
name=""
verbose=0
root_dir=${DEV_TOOLS_PROJECTS_DIR:-"$HOME/projects"}
cache_dir=${DEV_TOOLS_CACHE_DIR:-$XDG_CACHE_HOME/dev-tools}
dev_tools_dir=$(dirname $(readlink -f $(which $0)))

while [ "$1" != "" ]; do
    case $1 in
        -r | --regenerate )
            regenerate=1
            ;;
        -f | --folder )
            shift
            folder=$1
            ;;
        -d | --defaults )
            shift
            defaults=$1
            ;;
        -h | --help )
            usage
            exit
            ;;
        -v | --verbose )
            verbose=1
            ;;
        * )
            if [[ -n "$name" ]]; then
                echo "Too many arguments"
                exit 1
            fi
            name=$1
            ;;
    esac
    shift
done

if [[ -z $name ]]; then
    echo "no project specified"
    exit 1
fi

if [[ -z $folder ]]; then
    folder=$root_dir/$name
fi

if [[ ! -z $defaults ]]; then
    source $defaults $folder
fi

if [[ ! -e $cache_dir/$name || $regenerate -eq 1 ]]; then
    $dev_tools_dir/generator/generate.py $folder $name
fi

[[ $verbose -eq 1 ]] && env=" -e DEV_TOOLS_VERBOSE=1" || env=" -e DEV_TOOLS_VERBOSE=0"
while read e; do
    env="$env -e $e"
done <$cache_dir/$name

PROJECT_FOLDER=$(awk -F'=' '/PROJECT_FOLDER/ { print $2 }' $cache_dir/$name)
COMPOSE_PROJECT_NAME=$(awk -F'=' '/COMPOSE_PROJECT_NAME/ { print $2 }' $cache_dir/$name)

export PATH="$dev_tools_dir:$PATH"

cd $PROJECT_FOLDER

tmux new-session$env -A -s $COMPOSE_PROJECT_NAME
