#!/usr/bin/env bash

source wrapper

function main() {
    docker run --rm \
        -v yarn-cache:/home/node/.cache/yarn \
        -v yarn-conf:/home/node/.config/yarn \
        -v ssh-config:/home/node/.ssh:ro \
        -v "$(pwd)":/home/node/app \
        -u "$(id -u):$(id -g)" \
        -w "/home/node/app" \
        "$NODE_SERVICE" \
        yarn \
        "$@"
}

wrapper main "$@"
