#!/usr/bin/env bash

source $XDG_CONFIG_HOME/dockerenv/wrapper

function main() {
    docker run --rm \
        -v yarn-cache:/home/node/.cache/yarn \
        -v yarn-conf:/home/node/.config/yarn \
        -v ssh-config:/home/node/.ssh:ro \
        -v "$(pwd)":/home/node/app \
        -u "$(id -u):$(id -g)" \
        -w "/home/node/app" \
        node:19-alpine \
        yarn \
        "$@"
}

wrapper main "$@"
