#!/bin/bash

project="${1/#\~/$HOME}"

dockerdirs=("docker" "infrastructure")
for dir in $project/*; do
    for dockerdir in ${dockerdirs[@]}; do
        [ -d "$dir" ] || continue

        basedir=$(basename $dir)
        if [[ $basedir == *"$dockerdir"* ]]; then
            cd $project/$basedir

            if [ -e .env ]; then
                source "$(pwd)/.env"

                export COMPOSE_FILE="$(pwd)/docker-compose.yml"
                export COMPOSE_PROJECT_NAME="${BASEHOST//[^a-zA-Z0-9_]/}"
                export PROJECT_FOLDER=$(realpath ./$APPLICATION)
            fi
        fi
    done
done
